import numpy as np
hours = np.array([1, 2, 3, 4, 5])
marks = np.array([35, 45, 50, 60, 70])
print("Dataset")
print("Study Hours:", hours)
print("Marks:", marks)
x_mean = np.mean(hours)
y_mean = np.mean(marks)
print("\nMean Values")
print("Mean of Study Hours:", x_mean)
print("Mean of Marks:", y_mean)
slope = np.sum((hours - x_mean) * (marks - y_mean)) / np.sum((hours - x_mean) ** 2)
print("\nSlope")
print("Slope (m):", slope)
intercept = y_mean - (slope * x_mean)
print("\nIntercept")
print("Intercept (b):", intercept)
predicted_marks = slope * hours + intercept
print("\nPredicted Marks")
print(predicted_marks)
mse = np.mean((marks - predicted_marks) ** 2)
print("\nMean Squared Error")
print(mse)
print("\n========== Final Results ==========")
print("Slope (m):", slope)
print("Intercept (b):", intercept)
print("Predicted Marks:", predicted_marks)
print("Mean Squared Error:", mse)
